version: "3.8"

services:
    web:
        image: eazyip-web
        build: .
        ports:
            - 80:80
        volumes:
            - .\:/var/www/html/
        env_file:
            - ./db.env
        environment:
            - TZ=CET
