version: "3.8"

services:
    web:
        image: darlink-web
        # build: ./web
        ports:
            - 80:80
        volumes:
            - .\:/var/www/html/
        env_file:
            - ./db.env
        environment:
            - TZ=CET
